/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jni;

import java.util.Map;

public class App {
    public static native Map<String, String> getCpuInfo();

    static {
        System.loadLibrary("app");
    }

    public static void main(String[] args) {
        getCpuInfo().forEach((key, value) ->
                System.out.println(key.replace("machdep.cpu.", "") + " : " + value));
    }
}
