/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package constantPoolExtractor;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class App {

    public static void main(String[] args) {
        if (args.length!=1){
            System.out.println("Please provide filename");
            return;
        }
        String userDirectory = Paths.get("")
                .toAbsolutePath()
                .toString();
        System.out.println(userDirectory);
        File file = new File(args[0]);
        byte[] fileContent;
        try {
             fileContent = Files.readAllBytes(file.toPath());

        } catch (IOException e) {
            e.printStackTrace();
            return;
        }

        System.out.println(new ClassMetadata(fileContent).toString());
    }
}
