/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jmh;


public class IntegerRegexChecker implements IntegerChecker{
    @Override
    public boolean isInteger(String str) {
        return str.matches("^\\d+$");
    }
}
